name: DisableVillagerBreeding
version: '${version}'
main: rocks.gravili.disablevillagerbreeding.DisableVillagerBreeding
api-version: 1.21
folia-supported: true
authors: [ AlessioGR ]
permissions:
  disablevillagerbreeding.bypass:
    default: false
    description: Bypasses the villager breeding restriction
